"""creation des tables

Revision ID: 824385512d55
Revises: 
Create Date: 2025-11-25 00:10:32.258852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824385512d55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('pwd', sa.String(length=126), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titre')
    )
    op.create_table('etapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantite', sa.String(length=50), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('etapes')
    op.drop_table('recettes')
    op.drop_table('user')
    # ### end Alembic commands ###
